#!/usr/bin/env python

# --------------------------------------------------------------------------- #
#                         Obliging Ode & Unsung Anthem
# --------------------------------------------------------------------------- #
#
# This source file is part of the Obliging Ode and Unsung Anthem projects.
#
# Copyright (C) 2019 Antti Kivi
# All rights reserved
#
# --------------------------------------------------------------------------- #


"""
This tool sets up the dependencies of Obliging Ode and Unsung Anthem so you can
develop and build them.
"""

from __future__ import print_function

from datetime import datetime, time
import os
import sys
import time

from util import diagnostics

from util.date import date_difference, to_date_string

from support.variables import ANTHEM_SOURCE_ROOT


def main():
    """The entry function."""
    if sys.version_info.major == 2:
        if sys.version_info.minor < 7:
            diagnostics.fatal(
                "You're using Python {}, and the smallest supported version "
                "is {}".format(sys.version, "2.7"))
        else:
            diagnostics.warn("You're using Python {}".format(sys.version))
            diagnostics.warn(
                "You should really update to Python 3 to make the world a "
                "better place!")
            eol_date = datetime.strptime(
                "2020-01-01 00:00:00", "%Y-%m-%d %H:%M:%S")
            now = datetime.now()
            diagnostics.warn(
                "Also, the end of life of Python 2.7 is in {}, on 1 January, "
                "2020".format(to_date_string(date_difference(now, eol_date))))
    else:
        diagnostics.fine("You're using Python {}".format(sys.version))
        diagnostics.fine("You seem to have an excellent taste!")
    if not ANTHEM_SOURCE_ROOT:
        diagnostics.fatal(
            "Couldn't work out the source root directory (did you forget to "
            "set the '$ANTHEM_SOURCE_ROOT' environment variable?)")

    if not os.path.isdir(ANTHEM_SOURCE_ROOT):
        diagnostics.fatal(
            "The source root directory '{}' doesn't exist (did you forget to "
            "set $ANTHEM_SOURCE_ROOT environment variable?)".format(
                ANTHEM_SOURCE_ROOT))
    if any([(opt.startswith("--preset") or opt == "--show-presets")
            for opt in sys.argv[1:]]):
        return 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
